version: "3.8"

volumes:
  userdata:
    name: external_vol-domoticz-userdata
    external: true

networks:
  domoticz:
    name: "host"
    external: true

services:
  domoticz:
    image: domoticz/domoticz:2021-beta.13738
    env_file: external_env-all.env
    # environment:
    #   - LOG_PATH=/opt/domoticz/userdata/domoticz.log
    volumes:
      - userdata:/opt/domoticz/userdata
    # ports:
    #   - "8080:8080"
    networks:
      - domoticz
    # healthcheck:
    #   test: curl -f http://localhost:9090 || exit 1
    #   interval: 60s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 10m
    deploy:
      endpoint_mode: vip
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
        preferences:
          - spread: node.platform.os
      labels:
        "com.docker.stack.namespace": seed
      # resources:
      #   limits:
      #     cpus: '1'
      #     memory: 1024M
      #   reservations:
      #     cpus: '1'
      #     memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 2
        window: 60s
      rollback_config:
        parallelism: 0
        delay: 0s
        failure_action: pause
        monitor: 5m
        max_failure_ratio: 0
        order: stop-first
      update_config:
        parallelism: 0
        delay: 0s
        failure_action: rollback
        monitor: 5m
        max_failure_ratio: 0
        order: stop-first
